'use client';
import { useState, useEffect } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ArrowRight, Check, MessageCircle, Mail, Phone, FileText, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
const questions = [
 ['¿Qué incluye el estudio?','La propuesta reúne el cálculo actuarial de jubilación patronal y desahucio para la anualidad, los asientos contables y el análisis de impuestos diferidos. El alcance y los entregables se confirman en la cotización.'],
 ['¿Qué necesito para solicitar una cotización?','Para iniciar, indica la empresa, el número aproximado de trabajadores y el año del estudio. No necesitas adjuntar la nómina ni información personal de tus colaboradores en este formulario.'],
 ['¿Puedo solicitar la actualización de un estudio anterior?','Sí. Indícalo al contactar a Actuariosa. El estudio previo y los cambios de la nómina permitirán definir la información necesaria y el alcance de la actualización.'],
 ['¿Cuánto cuesta y en qué plazo se entrega?','El valor y la fecha de entrega se confirman según el tamaño de la nómina, el alcance y la información disponible. Solicita una propuesta para conocer ambos antes de contratar.'],
];
type Quote={company:string;employees:string;year:string};
function messageFor(q:Quote){return `Hola, Actuariosa. Quisiera solicitar una cotización para un estudio actuarial de jubilación patronal y desahucio.\nEmpresa: ${q.company.trim()}\nTrabajadores aproximados: ${q.employees}\nAño del estudio: ${q.year}\nMe interesa conocer el alcance, precio y plazo de entrega.`;}
export default function Details(){
 const [quote,setQuote]=useState<Quote>({company:'',employees:'',year:'2026'});
 const [message,setMessage]=useState('');
 const [copied,setCopied]=useState(false);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'prepare_quote_request',title:'Preparar solicitud de cotización',description:'Completa el formulario y muestra un borrador para revisar. No envía mensajes ni abre WhatsApp.',inputSchema:{type:'object',properties:{company:{type:'string',minLength:2,maxLength:120},employees:{type:'integer',minimum:1,maximum:1000000},year:{type:'integer',enum:[2024,2025,2026,2027]}},required:['company','employees','year'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const q=input as Record<string,unknown>;if(!q||typeof q.company!=='string'||q.company.trim().length<2||q.company.length>120||!Number.isInteger(q.employees)||Number(q.employees)<1||Number(q.employees)>1000000||![2024,2025,2026,2027].includes(Number(q.year))||Object.keys(q).some(k=>!['company','employees','year'].includes(k)))throw new Error('Indica una empresa válida, trabajadores entre 1 y 1000000 y un año entre 2024 y 2027.');const next={company:q.company,employees:String(q.employees),year:String(q.year)};const draft=messageFor(next);flushSync(()=>{setQuote(next);setMessage(draft);setCopied(false)});document.getElementById('contacto')?.scrollIntoView();return {status:'draft_ready',message:draft,sent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 const update=(key:keyof Quote,value:string)=>{setQuote(q=>({...q,[key]:value}));setMessage('');setCopied(false)};
 return <>
 <section className="process-band" id="proceso"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">UN CAMINO MÁS SIMPLE</p><h2>De tus datos<br/>a una visión más clara.</h2></div><p>Una consulta bien preparada es el primer paso. Así puedes empezar tu estudio con Actuariosa.</p></div><div className="steps">{[['01','Cuéntanos qué necesitas','Comparte el año del estudio y el tamaño aproximado de tu nómina.'],['02','Define el alcance','Confirma los entregables, el valor y la fecha de entrega en tu propuesta.'],['03','Prepara la información','Coordina con Actuariosa los datos necesarios y el canal para compartirlos.'],['04','Recibe tu estudio','Revisa los resultados actuariales y sus componentes contables.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="deliverables section wrap"><div><p className="eyebrow">MÁS ALLÁ DEL CÁLCULO</p><h2>Todo empieza con<br/><em>entender tus números.</em></h2><p className="body-copy">Un estudio actuarial ayuda a tu empresa a planificar las reservas para sus beneficios laborales posteriores al empleo.</p><a className="text-link" href="#contacto">Conoce el alcance para tu empresa <ArrowRight size={17}/></a></div><div className="report"><div className="report-title"><FileText size={24} strokeWidth={1.3}/><span>Tu estudio, de un vistazo<small>COMPONENTES DEL SERVICIO</small></span></div>{['Cálculo de jubilación patronal','Cálculo de desahucio','Asientos contables','Impuestos diferidos'].map((s,i)=><div className="report-row" key={s}><span>0{i+1}</span><strong>{s}</strong><Check size={15}/></div>)}<p>El alcance específico se confirma en la propuesta.</p></div></section>
 <section className="faq section wrap" id="preguntas"><div><p className="eyebrow">RESOLVEMOS TUS DUDAS</p><h2>La claridad comienza<br/><em>antes de contratar.</em></h2><p className="body-copy">¿Tienes una consulta más específica?</p><a className="text-link" href="mailto:actuariosa@gmail.com">Escríbenos <ArrowUpRight size={16}/></a></div><Accordion>{questions.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="contact-band" id="contacto"><div className="wrap contact-grid"><div className="contact-copy"><p className="eyebrow">EL SIGUIENTE PASO</p><h2>Planeemos hoy.<br/><em>Avancemos con certeza.</em></h2><p>Cuéntanos sobre tu empresa y solicita una propuesta acorde a lo que necesitas.</p><a href="mailto:actuariosa@gmail.com"><Mail size={17}/> actuariosa@gmail.com</a><a href="tel:+593988204349"><Phone size={17}/> 098 820 4349</a><a href="tel:+593984073702"><Phone size={17}/> 098 407 3702</a></div><form className="quote-form" onSubmit={e=>{e.preventDefault();setMessage(messageFor(quote));setCopied(false)}}><span className="form-kicker">HABLEMOS DE TU EMPRESA</span><h3>Solicita tu cotización</h3><p>Solo lo esencial para comenzar.</p><label htmlFor="company">Nombre de la empresa</label><Input id="company" name="company" placeholder="Ej. Mi Empresa S.A." required minLength={2} maxLength={120} value={quote.company} onChange={e=>update('company',e.target.value)}/><div className="form-row"><div><label htmlFor="employees">N.º de trabajadores</label><Input type="number" name="employees" id="employees" min={1} max={1000000} step={1} placeholder="Ej. 25" required value={quote.employees} onChange={e=>update('employees',e.target.value)}/></div><div><label htmlFor="year">Año del estudio</label><NativeSelect id="year" name="year" value={quote.year} onChange={e=>update('year',e.target.value)}>{['2024','2025','2026','2027'].map(y=><NativeSelectOption key={y} value={y}>{y}</NativeSelectOption>)}</NativeSelect></div></div><Button type="submit" className="button form-button">Preparar mi solicitud <ArrowRight size={17}/></Button><p className="privacy-note"><LockKeyhole size={13}/> Tus datos no se guardan en esta web. Revisa el mensaje antes de enviarlo por WhatsApp.</p>{message&&<div className="draft" role="status"><strong>Tu mensaje está listo para revisar</strong><p className="draft-message">{message}</p><a className="button whatsapp-action" href={`https://wa.me/593988204349?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer">Continuar en WhatsApp <ArrowUpRight size={15}/></a><Button type="button" variant="ghost" className="copy-button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true)}catch{setCopied(false)}}}>{copied?'Mensaje copiado':'Copiar mensaje'}</Button><p>La solicitud se envía únicamente cuando tú confirmas en WhatsApp.</p></div>}</form></div></section>
 <a className="floating-whatsapp" href="https://wa.me/593988204349?text=Hola%2C%20quisiera%20informaci%C3%B3n%20sobre%20sus%20estudios%20actuariales." target="_blank" rel="noopener noreferrer" aria-label="Contactar a Actuariosa por WhatsApp"><MessageCircle size={22}/><span>¿Conversamos?</span></a>
 </>;
}

