import PageMotion from '@/components/page-motion';
import Details from '@/components/details';
import { ArrowUpRight, ArrowRight, ChartNoAxesCombined, FileCheck2, Calculator, Check, MessageCircle, ChevronDown } from 'lucide-react';
const services=[{n:'01',icon:ChartNoAxesCombined,title:'Jubilación patronal y desahucio',text:'Calculamos las reservas para los beneficios laborales futuros de tus trabajadores.',tag:'ESTUDIO ACTUARIAL'},{n:'02',icon:FileCheck2,title:'Asientos contables',text:'Integra los resultados de tu estudio actuarial en los registros contables de tu empresa.',tag:'CONTABILIDAD'},{n:'03',icon:Calculator,title:'Impuestos diferidos',text:'Complementa tu estudio con el análisis de los efectos de impuestos diferidos.',tag:'ANÁLISIS TRIBUTARIO'}];
export default function Home(){return <><PageMotion/>
<header className="header"><div className="wrap nav-inner"><a href="#inicio" className="brand" aria-label="Actuariosa inicio"><img className="brand-logo" src="/brand/actuariosa.svg" width="1774" height="887" alt="Actuariosa · Actuarios del Ecuador"/></a><nav aria-label="Navegación principal"><a href="#servicios">Estudio actuarial <ChevronDown size={14}/></a><a href="#nosotros">Nosotros</a><a href="#proceso">Cómo trabajamos</a><a href="#preguntas">Preguntas frecuentes</a></nav><a className="button small" href="#contacto">Solicitar cotización <ArrowUpRight size={17}/></a></div></header>
<main id="inicio"><section className="hero"><div className="hero-background"/><div className="wrap hero-layout"><div className="hero-brand"><img className="hero-logo" src="/brand/actuariosa.svg" width="1774" height="887" alt="Actuariosa"/><p>Una visión clara para<br/>el futuro de tu empresa.</p></div><div className="hero-copy"><p className="eyebrow">CONSULTORÍA ACTUARIAL · ECUADOR</p><h1>Asesoría actuarial para tomar decisiones con <span>confianza.</span></h1><p className="hero-description">Planifica tus obligaciones de jubilación patronal y desahucio con estudios que conectan el cálculo actuarial con la realidad de tu empresa.</p><div className="hero-actions"><a className="button light" href="#servicios">Nuestros servicios <ArrowRight size={18}/></a><a className="button outline" href="#contacto">Contáctanos <MessageCircle size={18}/></a></div><div className="hero-highlights"><a href="#servicios"><span className="highlight-image study-image"/><strong>Jubilación patronal y desahucio</strong><span>Conoce qué incluye tu estudio <ArrowUpRight size={16}/></span></a><a href="#contacto"><span className="highlight-image planning-image"/><strong>El siguiente paso para tu empresa</strong><span>Prepara tu solicitud de cotización <ArrowUpRight size={16}/></span></a></div></div></div></section>
<div className="value-strip wrap"><div><ChartNoAxesCombined/><strong>Cálculo actuarial</strong><span>Jubilación patronal y desahucio</span></div><div><FileCheck2/><strong>Asientos contables</strong><span>Del estudio al registro financiero</span></div><div><Calculator/><strong>Impuestos diferidos</strong><span>Una visión contable completa</span></div></div>
<section className="about section wrap" id="nosotros"><div><p className="eyebrow">CONSULTORÍA ACTUARIAL</p><h2>Conocimiento actuarial al servicio de tu empresa.</h2><p className="body-copy">En Actuariosa elaboramos informes actuariales de jubilación patronal y desahucio para empresas del Ecuador. Nuestro estudio reúne el cálculo de la anualidad, los asientos contables y los impuestos diferidos.</p><div className="about-checks"><span><Check/> Reservas para beneficios laborales</span><span><Check/> Cálculo de la anualidad</span><span><Check/> Información para contabilidad</span><span><Check/> Planificación financiera</span></div><a className="button" href="#contacto">Conversemos sobre tu empresa <ArrowUpRight size={17}/></a></div><div className="about-photo"><img src="/consultation.png" alt="Imagen ilustrativa de una consulta con análisis de documentos financieros" loading="lazy"/><div className="about-caption"><ChartNoAxesCombined size={30}/><span>Anticipar tus compromisos.<br/><strong>Planificar con claridad.</strong></span></div></div></section>
<section className="services section" id="servicios"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">NUESTROS SERVICIOS</p><h2>Soluciones para tus<br/>compromisos laborales.</h2></div><p>Los componentes esenciales de tu estudio, explicados desde el primer contacto.</p></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.n}><div className="service-top"><s.icon size={35} strokeWidth={1.5}/><span>{s.n}</span></div><p className="micro">{s.tag}</p><h3>{s.title}</h3><p>{s.text}</p><a href="#contacto">Más información <ArrowRight size={18}/></a></article>)}</div></div></section>
<Details/></main><footer className="footer"><div className="wrap footer-main"><div className="footer-identity"><a href="#inicio" className="brand"><img className="footer-logo" src="/brand/actuariosa.svg" width="1774" height="887" alt="Actuariosa · Actuarios del Ecuador"/></a><div className="brand-downloads"><span>Descargar logo</span><a href="/brand/actuariosa.svg" download="actuariosa.svg">SVG</a><a href="/brand/actuariosa.png" download="actuariosa.png">PNG</a></div></div><div><strong>Servicios</strong><a href="#servicios">Estudios actuariales</a><a href="#servicios">Asientos contables</a><a href="#servicios">Impuestos diferidos</a></div><div><strong>Conoce más</strong><a href="#nosotros">Nosotros</a><a href="#proceso">Cómo trabajamos</a><a href="#preguntas">Preguntas frecuentes</a></div><div><strong>Contacto</strong><a href="mailto:actuariosa@gmail.com">actuariosa@gmail.com</a><a href="tel:+593988204349">098 820 4349</a><a href="tel:+593984073702">098 407 3702</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Actuariosa</span><span>Propuesta de sitio web · Versión de muestra</span></div></footer></>}



